### ISSUE TITLE
New features

### ISSUE THREAD

**Issue by greno4ka** [mpereira/tty-solitaire#12]
This game is awesome! But I found some possible enhancements.

- When I win, I want a big window with great letters, that are saying, that I WIN!!! Simple text in terminal "You won." is a little bit boring.
- Game can advise to play another game, when current ends (especially when you lost).
- Game can detect win and lost situations. (detecting of lost situations can be little bit difficult, but win situations are obvious: there no cards in stack and no hidden cards) For example in this position is very boring to drag cards up.
![_2017-10-27_14-17-14](https://user-images.githubusercontent.com/8567537/32096412-119debe8-bb0f-11e7-8ee8-a1dcba021f9f.png)

Please, dont stop development!

**Comment by mpereira** [comment]
@greno4ka,

I think those are great ideas. Unfortunately I currently don't have a lot of time to spend working on this project, but it should be easy enough for other people to contribute. I've created https://github.com/mpereira/tty-solitaire/issues/17 and https://github.com/mpereira/tty-solitaire/issues/18 based on your feedback so that we can track progress for this new functionality.

If you're feeling like contributing let me know and I'll help you out if you'd like!

> Please, dont stop development!

I won't 👍

**Comment by greno4ka** [comment]
If I get a free time, I'll try to contribute something. I think this can be interesting experience=) Thanks!
